# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_dia', models.CharField(choices=[('di', 'DIURNO'), ('tar', 'TARDE'), ('noc', 'NOCTURNO'), ('pr', 'PRUEBA')], default='di', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
