# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20160301_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado_dia',
            field=models.CharField(choices=[('di', 'diurno'), ('tar', 'tarde'), ('noc', 'nocturno'), ('pr', 'prueba')], default='di', max_length=20),
        ),
    ]
