# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20160301_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estado_dia',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='di', max_length=20),
        ),
    ]
