# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_auto_20160229_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='edad',
            field=models.IntegerField(help_text='Ingrese edad'),
        ),
    ]
