# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_auto_20160229_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='archivo',
            field=models.FileField(default=datetime.datetime(2016, 3, 1, 18, 41, 19, 60428, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prueba',
            name='usa_linux',
            field=models.BooleanField(default=datetime.datetime(2016, 3, 1, 18, 41, 43, 930327, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
