# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.TextField(help_text='Descripci\xf3n de la tarea', verbose_name='Tareas')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Todo Tarea',
                'verbose_name_plural': 'Todo Tareas',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Ingrese nombre ', max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, help_text='Ingrese apellido', max_length=100, null=True)),
                ('edad', models.IntegerField()),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='todoarticulo',
            name='fktodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuarios'),
        ),
    ]
