# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.TextField(help_text='Descripci\xf3n de la materia', verbose_name='Materia')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Todo Materia',
                'verbose_name_plural': 'Todo Materias',
            },
        ),
        migrations.RenameModel(
            old_name='usuarios',
            new_name='estudiante',
        ),
        migrations.RemoveField(
            model_name='todoarticulo',
            name='fktodo',
        ),
        migrations.DeleteModel(
            name='TodoArticulo',
        ),
        migrations.AddField(
            model_name='registro_materia',
            name='fkmateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.estudiante'),
        ),
    ]
