# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrado',
            new_name='Registro_docente',
        ),
    ]
